version: 0.2

phases:
  install:
    commands:
      - apk add --no-cache openssh
  pre_build:
    commands:
      - cat buildspec.yml
      - chmod 400 ./vapewild-magentopacker.bitbucket
  build:
    commands:
      - ls
      - pwd
      - mkdir /tmp/vm-multistore
      - mv * /tmp/vm-multistore
      - mv /tmp/vm-multistore ./vm-multistore
      - cd vapwild-magentopacker
      - make code_build_ami
