version: 0.2

phases:
  install:
    commands:
      - apk add --no-cache openssh
  pre_build:
    commands:
      - cat buildspec.yml
  build:
    commands:
      - ls
      - pwd
      - mkdir /tmp/vm-multistore
      - mv * /tmp/vm-multistore
      - mv /tmp/vm-multistore ./vm-multistore
      - git clone git@bitbucket.org:nbdev/vapewild-magentopacker.git
      - cd vapwild-magentopacker
      - make code_build_ami
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)
